# Data

> Quantities, characters, or symbols on which operations are performed by a 
> computer, considered collectively. Also (in non-technical contexts): 
> information in digital form.
>
> \- Oxford English Dictionary

If you are doing research, chances are you are going to be working with data
in some form or another. Even if you do not use the traditional rows and
columns people most often associate with "data", you certainly working with
information that has been translated into a form that is more easily shared
or stored for later use, aka data. 

One of the challenges of working with data is figuring out the best way, or at
least a good way, to store it. Thankfully, we have mostly left the 20th
century's favorite way of storing data: paper in filing cabinets. Our new
methods are definitely less flammable but but also can have a higher barrier to
entry. There are also a greater variety in types of data stores, which means you
need to make a decision on which one to use. Ultimately, the best way to store
your data will depend on the data you want to store, specifically the data type
and structure.

## Data Types

Your data's type tells the computer what sorts of operations make sense to do
with it. Common data types include integers, decimal or floating point numbers,
characters (text), Boolean values (TRUE and FALSE) and date/times. Data type
also influences how data is stored. Unlike other characteristics we will discuss later, an individual data point can have a type.

Data type is not necessarily inherent to a piece of information, though it is
often strongly suggested. For example, you can store the value of 1 as the
integer 1, the decimal 1.0, the text "1", the Boolean TRUE, or the date
1900-01-01 00:00:00. The underlying information is the same (1), but the
computer will treat each of these pieces of data differently. It will not allow
you to add "1" to another number, and it may have issues combining the integer
or decimal 1.0 with text. Text itself can only be stored as characters.

## Data Structures

> A data structure is a collection of data values, the relationships among them,
> and the functions or operations that can be applied to the data.
>
> Wikipedia

Unlike with data types, a single piece of data cannot have a data structure.
This is because data structure is about capturing relationships between data
points, there isn't any meaningful information to be gained from the
relationship of a data point with itself. There are four basic data structures:
tabular/columnar, graph, tree, and categorical/relational data. In practice,
data often exhibits traits from multiple data structures.

### Columnar/Tabular

```{r format_cars, echo=FALSE}

library(data.table)
library(stringr)

makers = c('chevrolet', 'honda', 'toyota', 'volkswagen', 'volvo')

car_origin = data.frame(origin=1:3, origin_region=c('USA', 'Europe', 'Japan'))

mpg_all = fread('data/autos_mpg.csv')

mpg = merge(mpg_all, car_origin, by='origin')

mpg$make = str_split_i(mpg$car_name, ' ' , i = 1)
mpg$model = str_split_fixed(mpg$car_name, ' ', 2)[, 2]

mpg = mpg[model_year==78 & make %in% makers, ]

coi = c('make', 'model', 'mpg', 'cylinders', 'horsepower', 'weight',
        'origin_region')

mpg = mpg[, ..coi]

setnames(mpg, 'origin_region', 'origin')


```


Tabular or columnar data is made up of rows and columns, collectively referred
to as a table. Each row represents an observation, and each column a measurement
from that observation. We 



### Graph

Graph data structure explicitly captures between entities. In graphs, 
relationships are defined by position and distance. Relationships can be 
directional 

### Tree 

Tree data is very similar to graph data in many ways. Trees also explicitly
capture relationships between entities. However, in trees the relationships
are hierarchical. The number of nodes separating an entity from a common root
defines that entity's place in the hierarchy. This is also 

### Categorical - Relational 

In categorical data, category membership is the organizing principle of the 
data structure. Entities can have membership in multiple categories, and
relationships are defined between categories instead of the entities themselves.
As such, relationships tend to represent complex processes rather than
individual entities.

## Picking a Data Structure

As mentioned previously, data represents information from the real world. And
all information in the real world can be thought of in a larger context, like
zooming out with a camera lens. You can use this context to identify the best
structure to use for your data. If you view your data as observation of some
larger phenomenon, tabular data could be a good fit. If you are more concerned
about how various entities relate to each other in the context of your research,
a graph may be more appropriate.

Additionally, many research questions are complex enough that one data structure
on its own may not be sufficient to capture all the information necessary to
answer the question. It it is very common to combine data structures to capture
more information that one could on its own. Most observation based data sets are
actually a combination of tabular data and categorical - relational data, which
captures information about the relationships between observations. Phylogenetic
trees, the data structure most commonly used in the study of evolution, is a
combination of the graph and tree data structures.




