---
title:  An Overview of Databases and Data Storage
author: [Elise Hellwig]
date: "`r Sys.Date()`"

github-repo: ucdavisdatalab/workshop_intro_to_databases
url: "https://ucdavisdatalab.github.io/workshop_intro_to_databases/"

lang: en-us

site: "bookdown::bookdown_site"
knit: "bookdown::render_book"
bibliography: data/references.bib  
---

# Workshop Description 

This workshop provides a broad overview of the various technologies for storing
and organizing different collections of data. We will discuss how data structure
and data types impact your storage options, when you should use a database, and
which platforms you might consider for your research. This workshop is a general
lecture with case studies and Q&A (no laptops necessary). This workshop is a
prerequisite for DataLab's [Intro to SQL for Querying Databases Workshop][sql],
and [Spatial SQL with SpatiaLite Workshop][spat_sql].

## Learning Objectives

After completing this workshop, you will be able to answer the following
questions:

  * What are the most common data structures people use?
  
  * Which data structures lend themselves to answering different types of
  research questions?
  
  * What is a database?
  
  * What are the differences between relational and noSQL databases?
  
  * When would a database help answer a particular research question?


[sql]: https://ucdavisdatalab.github.io/workshop_intro_to_sql/
[spat_sql]: https://ucdavisdatalab.github.io/Spatial_SQL/

## Prerequisites

No prerequisites or software required. This workshop is designed for researchers
with active or planned data collection and storage. 

<!-- Add something about bringing data with them? -->

## Credits

All images were created by Elise Hellwig unless otherwise noted. Movie
information courtesy of IMDb ([https://www.imdb.com][imdb]). Used with
permission for non-commercial purposes only.

[imdb]: https://www.imdb.com

### References

::: {#refs}
:::
